### ISSUE TITLE
A better way to handle Entrance Rando

### ISSUE THREAD

**Issue by TheT113** [wooferzfg/tww-rando-tracker#40] opened 2019-11-14 02:42 UTC
Instead of the "View Entrances" button, have each entrance (as it appears on the View Entrances list) listed under it's island, instead. If so, adding some kind of indicator to the map showing which areas have entrances to check (whether it's merely, adding a number to the number of checks on that tile, or adding a separate value).

As an additional ideal feature, I'd love to see: when you mark an entrance as belonging to a specific (non-dungeon) cave, moving that cave's checks to the new location would be an incredibly useful feature to make it less tedious. But I understand why this would be harder.

**Comment by wooferzfg** [comment] 2020-08-08 20:03
Duplicate of #27

**Closed by wooferzfg** 2020-08-08 20:03 UTC
Labels: enhancement

**Comment by wooferzfg** [comment] 2023-12-14 03:26
Planning to implement it this way: https://github.com/wooferzfg/tww-rando-tracker/issues/270#issuecomment-1855025432
